"""added protocol column to cloudstorage

Revision ID: 44bd8e7e1e57
Revises: 58eebb54e950
Create Date: 2024-01-24 17:09:44.157660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44bd8e7e1e57'
down_revision = '58eebb54e950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud_storage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protocol', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud_storage', schema=None) as batch_op:
        batch_op.drop_column('protocol')

    # ### end Alembic commands ###
