"""cloud storage polymorphic model

Revision ID: 467ccc7c19c5
Revises: 44bd8e7e1e57
Create Date: 2024-02-27 15:28:09.016244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467ccc7c19c5'
down_revision = '44bd8e7e1e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ftp_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=250), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['cloud_storage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webdav_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('directory', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['cloud_storage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cloud_storage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protocol_type', sa.String(length=30), nullable=False))
        batch_op.drop_column('url')
        batch_op.drop_column('protocol')
        batch_op.drop_column('username')
        batch_op.drop_column('password')
        batch_op.drop_column('directory')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud_storage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('directory', sa.VARCHAR(length=250), nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('protocol', sa.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=250), nullable=False))
        batch_op.drop_column('protocol_type')

    op.drop_table('webdav_storage')
    op.drop_table('ftp_storage')
    # ### end Alembic commands ###
