"""tasks

Revision ID: 876b2357f8ca
Revises: c283a53762f7
Create Date: 2024-04-22 16:46:03.195282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876b2357f8ca'
down_revision = 'c283a53762f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_task', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
