"""musictasks timestamp

Revision ID: 9b890059efab
Revises: 8751e347254a
Create Date: 2024-06-11 20:31:24.046090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b890059efab'
down_revision = '8751e347254a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_music_task_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_music_task_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
