"""added localstorage option

Revision ID: a0d92bfe78a4
Revises: 9c7a3820e8bb
Create Date: 2024-06-27 21:04:28.374506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d92bfe78a4'
down_revision = '9c7a3820e8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['cloud_storage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('local_storage')
    # ### end Alembic commands ###
