"""MusicTasks

Revision ID: bd67f953f5c5
Revises: 467ccc7c19c5
Create Date: 2024-04-03 20:59:35.532997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd67f953f5c5'
down_revision = '467ccc7c19c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('music_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_music_task_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_music_task_name'))

    op.drop_table('music_task')
    # ### end Alembic commands ###
